# Arrays and Matrices

The following exercises cover the basics of how you will create and work with "matrices" in Python.  Here, we will actually be working with ndarrays (numpy arrays).  For our purposes, we can generally treat them as matrices.

## Numpy

In [1]:
import numpy as np

## Dimensions of numpy arrays

"Row" and "Column" vectors are a little different in Python (`numpy`). It is important to understand that rows ($1 \times n$) and columns ($m \times 1$) have 2 dimensions. A Row has 1 row and n columns, and a column has m rows and 1 column. Usually, we don't *actually* need a structure that has the true 2D shape of a row or a column. Unless we are doing something particular with a linear algebra operation, we probably aren't overly concerned about whether things are rows are columns, so we can typically get away with creating a 1 dimensional array. It is important to understand that, with a 1D array, there is only a length associated with it; it does not have a second dimension, so it is neither a row nor a column.  It is a 1 dimensional array--when I last worked in Matlab, there was no such thing as a 1D array, so this dimensionality was new to me in Python and thus confusing. 

<div class = "alert alert-block alert-info">
    <b>Be Aware</b>: If you do a linear algebra operation that requires a row or a column, Python will often try do decide whether your 1D array should be treated as a row or a column.  Just be aware of that...
    </div>

In [2]:
A = np.array([1, 2, 3, 4])
print(A)

[1 2 3 4]


## Attributes of numpy arrays

`array_name.attribute_name`

In [3]:
print(A.size, '\n') #Returns the "size" of the array, i.e., the number of elements in it
print(A.ndim, '\n') #Returns the number of dimensions; should be 1 here
print(A.shape) #Returns a tuple of dimensions of (4, ) (elements in 1st dimension (rows), elements in 2nd (columns), etc)

4 

1 

(4,)


## Creating a 2D numpy array: rows and columns

Usually a 1D array will suffice in instances where we need to collect an array of scalars without a specific 2D shape to their layout or organization (where we might have used a row [1, 2, 3, 4] or a column [1; 2; 3; 4] in Matlab). If we ever need to create either a row or a column in Python, we have to remember that each of these things has a two dimensional shape associated with it.  2D arrays are created by passing a "list-of-lists" architecture into the array constructor.  The general idea is that each "row" in a 2D array is passed as a separate list into a top-level list.

In [4]:
row = np.array([[1, 2, 3, 4]])       #this is a row shape = (1,4)
col = np.array([[1], [2], [3], [4]]) #this is a column with shape (4,1) 
print(row, '\n')
print(row.shape, '\n')
print(col, '\n')
print(col.shape)

[[1 2 3 4]] 

(1, 4) 

[[1]
 [2]
 [3]
 [4]] 

(4, 1)


## Matrices in Python

Now that we know how to create a 2D array, it is pretty straightforward to create a matrix.  We basically do this by stacking rows together with a list-of-lists layout. Note again the bracket inside of brackets for a 2D system `np.array([[]])` -- when creating a matrix in the array environment, each row of the matrix should be passed to the array constructor as a comma separated list:

In [5]:
mat1 = np.array([[1, 2], [3, 4], [5, 6]])
print(mat1, '\n')
print(mat1.size, '\n')
print(mat1.shape, '\n')
print(mat1.ndim)

[[1 2]
 [3 4]
 [5 6]] 

6 

(3, 2) 

2


## hstack and vstack

Sometimes we need to stack rows or columns to create a matrix; we can do this with `np.vstack()` (stack rows) and `np.hstack()` (stack columns).

In [7]:
mat2 = np.vstack([row, row])
mat3 = np.hstack([col, col])
# print(mat2, '\n')
# print(mat2.shape, '\n')
print(mat3, '\n')
print(mat3.shape)

[[1 1]
 [2 2]
 [3 3]
 [4 4]] 

(4, 2)


## Matrix operations and Linear Algebra

I always struggle some in teaching Python because I am never actually teaching linear algebra, so I never want to go into a lot of detail about matrix/vector/row operations; however, my typical courses are in reactor design and kinetics, which benefit from knowing and using linear algebra. 

### Transpose of a column

In [10]:
print(col, '\n')
print(np.transpose(col), '\n')
print(col.T)

[[1]
 [2]
 [3]
 [4]] 

[[1 2 3 4]] 

[[1 2 3 4]]


### Transpose a Matrix

In [12]:
print(mat1, '\n')
print(mat1.T, '\n')
print(np.transpose(mat1))

[[1 2]
 [3 4]
 [5 6]] 

[[1 3 5]
 [2 4 6]] 

[[1 3 5]
 [2 4 6]]


### Transposes work on 2D structures...

In [13]:
print(A)
print(A.T)

[1 2 3 4]
[1 2 3 4]


### Determinants and Matrix Inversion

In [17]:
square_mat = np.array([[1, 2, 3], [9, 10, 16], [7, 28, 3]]) #create a square matrix
print(square_mat, '\n')
print(np.linalg.det(square_mat), '\n') #determinant; is it nonzero? Then we can invert.
print(np.linalg.inv(square_mat), '\n') #invert matrix 

[[ 1  2  3]
 [ 9 10 16]
 [ 7 28  3]] 

298.00000000000006 

[[-1.40268456  0.26174497  0.00671141]
 [ 0.2852349  -0.06040268  0.03691275]
 [ 0.61073826 -0.04697987 -0.02684564]] 



## Indexing in 2DArrays

When you work with arrays as your primary data type, you will frequently need to access or reference specific elements in those arrays. You do so by specifying their index in (row,column) format; you can also use list indexing conventions with a numpy array.  

In [20]:
mat1[0, 0] #3rd row, 2nd column in mat1
# mat1[2][1] #np.arrays retain list indexing...

1

### Negative Indexing in Arrays


In [21]:
print(A[-1])          #final element in 1D array
print(col[-1, 0])     #final row in a column vector
print(row[0, -1])     #final columin in a row vector
print(mat3[2,-1])     #third row in the final column of a matrix
print(mat1[-1,1])     #second column in the final row of a matrix
print(mat2[-1, -1])   #final column in final row of a matrix
print(mat2[:, -2])    #All rows in second to last column of matrix

4
4
4
3
6
4
[3 3]


### Slicing in arrays

This works very similar to the way it does with lists.

In [24]:
numbers = np.array([5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
numbers[0:4] #First four elements (indices 0, 1, 2, 3). Remember, Python excludes the final index in this notation
numbers[5:] #Indices 9 to end; With this notation, we return the last element

array([10, 11, 12, 13, 14])

## Automated array generation

### Using Iterables

In [25]:
numbers = np.array(range(0, 25, 2)) #range(start, stop, step size); all int format
print(numbers)
print(numbers.shape)
print(numbers.ndim)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24]
(13,)
1



### `np.linspace()`

`np.linspace(lower, upper, number of elements)`

In [31]:
fives = np.linspace(0, 50, 12, dtype = 'float') #np.linspace(lower element, upper element, number of steps).
print(fives, '\n')
print(fives.shape, '\n')
print(fives.ndim)

[ 0.          4.54545455  9.09090909 13.63636364 18.18181818 22.72727273
 27.27272727 31.81818182 36.36363636 40.90909091 45.45454545 50.        ] 

(12,) 

1


### `np.logspace()`

For example, to create a set of 11 numbers spaced at $10^{-5}$, $10^4$, etc., up to $10^5$:

In [27]:
logset = np.logspace(-5, 5, 11) #np.logspace(lower power of base, upper power of base, number of elements)
print(logset, '\n')

lnset = np.logspace(-5, 5, 11, base = np.exp(1))
print(lnset)

[1.e-05 1.e-04 1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03 1.e+04
 1.e+05] 



### `np.zeros()`

Often, we want to define matrices or vectors that contain zero.  These are easy to generate in Python (`numpy.zeros(shape)`), where shape is either an integer (for a 1D array) or a tuple for an ND array


In [36]:
np.zeros(3)       #1D array with 3 zeros
np.zeros((1,3))   #2D array (1x3 row) with 3 zeros
np.zeros((3,1))   #2D array (3x1 column) with 3 zeros
np.zeros((3,3))   #2D array (3x3 matrix) with 9 zeros
np.zeros((3,3,3)) #3D array (3 copies of 3x3 matrix, each with 9 zeros)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### `np.ones()`

Similarly, you can generate the same structures filled with 1's.

In [38]:
np.ones(3)
np.ones((1,3))
np.ones((3,1))
np.ones((3,3))
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

As an example, this might be a place where you'd like to specify an integer format with the  `dtype` keyword argument, which works with most numpy.array constructors.

In [39]:
np.ones((3, 3), dtype = 'int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### The Identity Matrix

In [40]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.eye(2)
np.eye(5)
np.eye(5, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## Math on Numpy arrays

### Elementwise operations (broadcasting)

When performing mathematical operations on numpy arrays, ***the default is that they use element-by-element operations instead of linear algebra operations (e.g., matrix multiplication, matrix exponential, etc.)***.  This is best illustrated with an example.  Look at the output of the following:

In [44]:
print(col+col, '\n') #This will add each element of col to itself
print(col*col, '\n') #same as above with multiplication
print(col**3, '\n')  #same as above, but cubing each element of column
print(col/col, '\n') #divide each element of col by each element of column
print(col*row, '\n') #you might think this is matrix multiplication, but it's not; it is element by element
print(mat1*mat1, '\n') #this is also not a matrix multiplication, it is element by element operation

[[2]
 [4]
 [6]
 [8]] 

[[ 1]
 [ 4]
 [ 9]
 [16]] 

[[ 1]
 [ 8]
 [27]
 [64]] 

[[1.]
 [1.]
 [1.]
 [1.]] 

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]] 

[[ 1  4]
 [ 9 16]
 [25 36]] 



### Matrix Math

If you want to multiply two matrices using linear algebra rules, it has special syntax.  First, you have to remember that dimensions are important when multiplying rows, columns, and matrices.  They all have to be correct. Their product returns a new matrix where each element (i,j) is the dot product of  row (i) and column (j). For this reason, the two matrices you intend to multiply must have dimensions (m x n) * (n x p), and their product returns a new matrix of dimensions (m x p).  As an illustration, a matrix can be multiplied by its transpose to return a square matrix (but the order matters):

In [45]:
mat1       #A 3x2 matrix
mat1.T     #A 2x3 matrix

array([[1, 3, 5],
       [2, 4, 6]])

#### Matrix Multiplication

There are various ways to perform matrix multiplication; all are more-or-less equivalent for our purposes; I generally use the @ syntax since it is the cleanest and easiest to understand when I read the code.

In [48]:
np.matmul(mat1, mat1.T) #their product is a 3x3 matrix
mat1@mat1.T             #equivalent to above; recent addition to python as of 3.5
np.dot(mat1, mat1.T)    #dot product of rows and columns; similar to above.

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [50]:
mat1@mat1.T
mat1.T@mat1

array([[35, 44],
       [44, 56]])

In [52]:
row*col.T  #(1 x 4) row * (1 x 4) row, elementwise
row@col.T #(1 x 4) x (1 x 4) matrix product; will return an error

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 4)

#### Solving systems of linear equations

In many cases, our systems can be described using a system of nonlinear equations.  An example that I use all the time in Kinetics is linear regression, which involves solving a linear system of equations by matrix inversion.  Since this is so commonly encountered, we'll briefly introduce it here.

Let's say we have the following system of equations:

\begin{align}
    2x + 3y + 4z &= 25 \\
    15x + 12y - 10z &= 11 \\
    1.6x - 4y + 23.2z &= -5
\end{align}

This could be expressed in Matrix Form:

$$AX = B$$

Where:

$$A = 
    \begin{bmatrix} 
    2 & 3 & 4 \\
    15 & 12 & -10 \\
    1.6 & 4 & 23.2 \\
    \end{bmatrix}
$$

$$X = 
    \begin{bmatrix} 
    x \\
    y \\
    z \\
    \end{bmatrix}
$$

$$B = 
    \begin{bmatrix} 
    25 \\
    11 \\
    -5 \\
    \end{bmatrix}
$$


This problem can be solved for X as follows:

$$X = A^{-1}B$$

But it is generally computationally inefficient to invert matrices, so the preferred solution in Python is using `np.linalg.solve()`:

In [54]:
A = np.array([[2, 3, 4], [15, 12, -10], [1.6, 4, 23.2]])
B = np.array([[25], [11], [-5]])
print(A, '\n')
print(B, '\n')
X = np.linalg.solve(A, B) #functionally equivalent to np.linalg.inv(A)@B
print(X, '\n')
print(A@X)

[[  2.    3.    4. ]
 [ 15.   12.  -10. ]
 [  1.6   4.   23.2]] 

[[25]
 [11]
 [-5]] 

[[-26.57671233]
 [ 31.02739726]
 [ -3.73219178]] 

[[25.]
 [11.]
 [-5.]]
